; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf
board_upload.flash_size = 16MB
;board_build.partitions = default_16MB.csv
board_build.partitions = partitions.csv
board_build.sdkconfig = sdkconfig.defaults
build_flags=
    -D BOARD_HAS_PSRAM ;activate support for the psram
    -mfix-esp32-psram-cache-issue ;use the camera of the esp32-s3
    -DCONFIG_DEFAULT_HUMAN_FACE_DETECT_MODEL=0
    -DCONFIG_FLASH_HUMAN_FACE_DETECT_MSRMNP_S8_V1=1
    -DCONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_PARTITION=1
    -DCONFIG_HUMAN_FACE_DETECT_MODEL_LOCATION=1
    -DCONFIG_DEFAULT_HUMAN_FACE_FEAT_MODEL=0
    -DCONFIG_FLASH_HUMAN_FACE_FEAT_MFN_S8_V1=1
    -DCONFIG_HUMAN_FACE_FEAT_MODEL_IN_FLASH_PARTITION=1
    -DCONFIG_HUMAN_FACE_FEAT_MODEL_LOCATION=1
    
  
